{% set name = "pyfakefs" %}
{% set version = "5.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24774c632f3b67ea26fd56b08115ba7c339d5cd65655410bca8572d73a1ae9a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  source_files:
    - pyfakefs
  imports:
    - pyfakefs
  commands:
    - pip check
    - python -m pyfakefs.tests.all_tests
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pyfakefs
  doc_url: https://pytest-pyfakefs.readthedocs.io/
  license: Apache-2.0
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.
  description: |
    Pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and macOS.

extra:
  recipe-maintainers:
    - tswast
    - thewchan
