{% set name = "pyfakefs" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4623770fb9994887e883d4193cc6a3746014b4287f94a73e0de04a0aa3c8a56a

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - pyfakefs

about:
  home: https://github.com/jmcgeheeiv/pyfakefs
  license: Apache-2.0
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.

  description: |
    pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and MacOS.

  doc_url: http://jmcgeheeiv.github.io/pyfakefs/
  dev_url: https://github.com/jmcgeheeiv/pyfakefs

extra:
  recipe-maintainers:
    - tswast
