schema_version: 1

context:
  name: pyfakefs
  version: "6.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 1c166fdba85f3f288f89b2a410e05712914d1f7ea77b920e960fe0cbbea1294d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pyfakefs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.
  description: |
    Pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and macOS.


  homepage: https://github.com/pytest-dev/pyfakefs
  documentation: https://pytest-pyfakefs.readthedocs.io/

extra:
  recipe-maintainers:
    - tswast
    - thewchan
