schema_version: 1

context:
  name: pyfakefs
  version: "5.9.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b458b11abc8862d4d8500816170a9b25e10d07437332b9dffd651069f3d4c40c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=45
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pyfakefs
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - pyfakefs
    requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python -m pyfakefs.tests.all_tests

about:
  license: Apache-2.0
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.
  description: |
    Pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and macOS.


  homepage: https://github.com/pytest-dev/pyfakefs
  documentation: https://pytest-pyfakefs.readthedocs.io/

extra:
  recipe-maintainers:
    - tswast
    - thewchan
